import type {
  Action,
  Audit,
  Barrier,
  Bowtie,
  Consequence,
  DegradationControl,
  DegradationFactor,
  Incident,
  Moc,
  PerformanceStandard,
  Risk,
  Scenario,
  Threat,
  Verification,
  AiSuggestion,
} from '@bowtie/shared';

export const CHEMICAL_SCENARIO: Scenario = {
  id: 'sc-chemical',
  industry: 'chemical_plant',
  name: 'Hartwell Specialty Chemicals — Plant 4',
  description: 'Specialty chemicals manufacturing site; chlorine and EDC handling.',
};

export const CHEMICAL_BOWTIES: Bowtie[] = [
  {
    id: 'bt-chm-001',
    scenarioId: 'sc-chemical',
    title: 'Chlorine Release from Bulk Storage',
    hazard: 'Liquefied chlorine under pressure (90 t bulk storage, T-401)',
    topEvent: 'Loss of containment of bulk chlorine',
    assetOrProcess: 'Chlorine storage area — Plant 4 East',
    ownerId: 'u-bo-002',
    approvalState: 'approved',
    riskBeforeBarriers: 25,
    riskCurrent: 15,
    riskAfterBarriers: 10,
    riskTarget: 6,
    threatIds: ['th-chm-001', 'th-chm-002', 'th-chm-003'],
    consequenceIds: ['cq-chm-001', 'cq-chm-002', 'cq-chm-003'],
    preventiveBarrierIds: ['br-chm-001', 'br-chm-002', 'br-chm-003'],
    mitigativeBarrierIds: ['br-chm-004', 'br-chm-005', 'br-chm-006'],
    lastRevisedAt: '2026-03-04',
    nextReviewDue: '2026-09-04',
    changesPendingMoc: true,
    publishedAt: null,
  },
];

export const CHEMICAL_THREATS: Threat[] = [
  {
    id: 'th-chm-001',
    bowtieId: 'bt-chm-001',
    description: 'Tank overpressure due to thermal expansion / external fire',
    preventiveBarrierIds: ['br-chm-001', 'br-chm-002'],
  },
  {
    id: 'th-chm-002',
    bowtieId: 'bt-chm-001',
    description: 'Loading-arm hose rupture during tanker offloading',
    preventiveBarrierIds: ['br-chm-003'],
  },
  {
    id: 'th-chm-003',
    bowtieId: 'bt-chm-001',
    description: 'External impact (vehicle / dropped load on tank shell)',
    preventiveBarrierIds: [],
  },
];

export const CHEMICAL_CONSEQUENCES: Consequence[] = [
  {
    id: 'cq-chm-001',
    bowtieId: 'bt-chm-001',
    description: 'Worker exposure with acute health effects',
    severity: 'major',
    mitigativeBarrierIds: ['br-chm-004', 'br-chm-005'],
  },
  {
    id: 'cq-chm-002',
    bowtieId: 'bt-chm-001',
    description: 'Off-site community exposure (chlorine plume drift)',
    severity: 'catastrophic',
    mitigativeBarrierIds: ['br-chm-005', 'br-chm-006'],
  },
  {
    id: 'cq-chm-003',
    bowtieId: 'bt-chm-001',
    description: 'Asset damage and prolonged plant outage',
    severity: 'major',
    mitigativeBarrierIds: ['br-chm-004'],
  },
];

export const CHEMICAL_BARRIERS: Barrier[] = [
  {
    id: 'br-chm-001',
    scenarioId: 'sc-chemical',
    bowtieIds: ['bt-chm-001'],
    name: 'Tank integrity inspection (API 653)',
    type: 'preventive',
    function: 'procedural',
    criticality: 'critical',
    ownerId: 'u-bo-002',
    description: 'External and internal inspection per API 653 with UT thickness mapping.',
    performanceStandardId: 'ps-chm-001',
    healthScore: 86,
    status: 'yellow',
    withCompensatory: false,
    lastVerifiedAt: '2025-10-15',
    nextVerificationDue: '2026-10-15',
    failedTests: 0,
    openCriticalFindings: 0,
    evidenceUrl: null,
    aiOriginSuggestionId: null,
    gapRecord: null,
  },
  {
    id: 'br-chm-002',
    scenarioId: 'sc-chemical',
    bowtieIds: ['bt-chm-001'],
    name: 'Pressure Safety Valve (PSV) testing',
    type: 'preventive',
    function: 'hardware',
    criticality: 'critical',
    ownerId: 'u-bo-002',
    description: '2x100% PSVs on T-401 with annual bench testing.',
    performanceStandardId: 'ps-chm-001',
    healthScore: 92,
    status: 'green',
    withCompensatory: false,
    lastVerifiedAt: '2026-02-02',
    nextVerificationDue: '2027-02-02',
    failedTests: 0,
    openCriticalFindings: 0,
    evidenceUrl: null,
    aiOriginSuggestionId: null,
    gapRecord: null,
  },
  {
    id: 'br-chm-003',
    scenarioId: 'sc-chemical',
    bowtieIds: ['bt-chm-001'],
    name: 'Tanker offloading procedure & hose integrity check',
    type: 'preventive',
    function: 'procedural',
    criticality: 'high',
    ownerId: null,
    description: 'Pre-offload hose integrity inspection plus dual-operator procedure.',
    performanceStandardId: null,
    healthScore: 60,
    status: 'red',
    withCompensatory: false,
    lastVerifiedAt: '2025-12-01',
    nextVerificationDue: '2026-04-01',
    failedTests: 0,
    openCriticalFindings: 1,
    evidenceUrl: null,
    aiOriginSuggestionId: null,
    /** Documented gap — owner reassignment in progress. */
    gapRecord: {
      ownerId: 'u-rm-001',
      targetResolutionDate: '2026-05-15',
      linkedActionId: 'ac-chm-002',
      notes: 'Barrier owner left the company; interim procedure custodian named in MOC moc-chm-001.',
    },
  },
  {
    id: 'br-chm-004',
    scenarioId: 'sc-chemical',
    bowtieIds: ['bt-chm-001'],
    name: 'Toxic gas detection — perimeter & area',
    type: 'mitigative',
    function: 'instrumented',
    criticality: 'critical',
    ownerId: 'u-bo-002',
    description: 'Cl2-specific point detection at 0.5 ppm with perimeter open-path monitoring.',
    performanceStandardId: 'ps-chm-002',
    healthScore: 95,
    status: 'green',
    withCompensatory: false,
    lastVerifiedAt: '2026-03-18',
    nextVerificationDue: '2026-09-18',
    failedTests: 0,
    openCriticalFindings: 0,
    evidenceUrl: null,
    aiOriginSuggestionId: null,
    gapRecord: null,
  },
  {
    id: 'br-chm-005',
    scenarioId: 'sc-chemical',
    bowtieIds: ['bt-chm-001'],
    name: 'Caustic scrubber for chlorine vent stream',
    type: 'mitigative',
    function: 'hardware',
    criticality: 'critical',
    ownerId: 'u-bo-002',
    description: 'Caustic scrubber rated 5x design release; auto-startup on Cl2 detection.',
    performanceStandardId: 'ps-chm-002',
    healthScore: 90,
    status: 'green',
    withCompensatory: false,
    lastVerifiedAt: '2026-02-22',
    nextVerificationDue: '2026-08-22',
    failedTests: 0,
    openCriticalFindings: 0,
    evidenceUrl: null,
    aiOriginSuggestionId: null,
    gapRecord: null,
  },
  {
    id: 'br-chm-006',
    scenarioId: 'sc-chemical',
    bowtieIds: ['bt-chm-001'],
    name: 'Site-wide evacuation alarm & community notification',
    type: 'recovery',
    function: 'organizational',
    criticality: 'high',
    ownerId: 'u-bo-002',
    description: 'Site siren plus automated community telephone notification within 15 min.',
    performanceStandardId: null,
    healthScore: 78,
    status: 'yellow',
    withCompensatory: false,
    lastVerifiedAt: '2026-01-15',
    nextVerificationDue: '2026-07-15',
    failedTests: 0,
    openCriticalFindings: 0,
    evidenceUrl: null,
    aiOriginSuggestionId: null,
    gapRecord: null,
  },
];

export const CHEMICAL_DEGRADATION_FACTORS: DegradationFactor[] = [
  {
    id: 'df-chm-001',
    barrierId: 'br-chm-005',
    description: 'Caustic strength drift — efficacy declines below 18% NaOH',
    degradationControlIds: ['dc-chm-001'],
    aiOriginSuggestionId: null,
  },
];

export const CHEMICAL_DEGRADATION_CONTROLS: DegradationControl[] = [
  {
    id: 'dc-chm-001',
    degradationFactorId: 'df-chm-001',
    name: 'Weekly caustic strength sampling + auto top-up',
    function: 'instrumented',
    ownerId: 'u-bo-002',
    status: 'green',
    aiOriginSuggestionId: null,
  },
];

export const CHEMICAL_RISKS: Risk[] = [
  {
    id: 'rk-chm-001',
    scenarioId: 'sc-chemical',
    title: 'Major chlorine release with off-site impact',
    category: 'safety',
    inherentRisk: 25,
    currentRisk: 15,
    residualRisk: 10,
    targetRisk: 6,
    ownerId: 'u-rm-001',
    bowtieIds: ['bt-chm-001'],
    treatmentPlan: 'Resolve barrier ownership gap on offloading procedure; complete MOC moc-chm-001.',
    acceptanceStatus: 'pending',
  },
  {
    id: 'rk-chm-002',
    scenarioId: 'sc-chemical',
    title: 'Reputational impact from community evacuation',
    category: 'reputation',
    inherentRisk: 15,
    currentRisk: 9,
    residualRisk: 6,
    targetRisk: 4,
    ownerId: 'u-rm-001',
    bowtieIds: ['bt-chm-001'],
    treatmentPlan: 'Quarterly drill with municipality emergency services.',
    acceptanceStatus: 'accepted',
  },
];

export const CHEMICAL_ACTIONS: Action[] = [
  {
    id: 'ac-chm-001',
    scenarioId: 'sc-chemical',
    title: 'Replace chlorine offloading hose set after pressure test failure',
    source: 'verification',
    bowtieId: 'bt-chm-001',
    barrierId: 'br-chm-003',
    ownerId: 'u-bo-002',
    dueDate: '2026-05-10',
    priority: 'high',
    status: 'in_progress',
    evidence: null,
    effectivenessReview: null,
  },
  {
    id: 'ac-chm-002',
    scenarioId: 'sc-chemical',
    title: 'Reassign procedure owner for offloading procedure (ex-employee gap)',
    source: 'review',
    bowtieId: 'bt-chm-001',
    barrierId: 'br-chm-003',
    ownerId: 'u-rm-001',
    dueDate: '2026-05-15',
    priority: 'critical',
    status: 'open',
    evidence: null,
    effectivenessReview: null,
  },
  {
    id: 'ac-chm-003',
    scenarioId: 'sc-chemical',
    title: 'Run joint emergency drill with municipal emergency services',
    source: 'review',
    bowtieId: 'bt-chm-001',
    barrierId: 'br-chm-006',
    ownerId: 'u-bo-002',
    dueDate: '2026-07-30',
    priority: 'medium',
    status: 'open',
    evidence: null,
    effectivenessReview: null,
  },
];

export const CHEMICAL_VERIFICATIONS: Verification[] = [
  {
    id: 'vf-chm-001',
    scenarioId: 'sc-chemical',
    date: '2026-02-22',
    barrierId: 'br-chm-005',
    performedById: 'u-bo-002',
    method: 'test',
    result: 'pass',
    evidence: 'Scrubber wet test 2026-Q1',
    nextDue: '2026-08-22',
    comments: 'Auto-start within 12 s; caustic strength 21% NaOH.',
  },
  {
    id: 'vf-chm-002',
    scenarioId: 'sc-chemical',
    date: '2025-12-01',
    barrierId: 'br-chm-003',
    performedById: 'u-au-001',
    method: 'inspection',
    result: 'fail',
    evidence: 'Hose pressure test report HPT-2025-12-01',
    nextDue: '2026-04-01',
    comments: 'Hose H-3 failed pressure test; replacement ordered.',
  },
];

export const CHEMICAL_PERFORMANCE_STANDARDS: PerformanceStandard[] = [
  {
    id: 'ps-chm-001',
    scenarioId: 'sc-chemical',
    name: 'PS-CL-01 Chlorine containment integrity',
    category: 'reliability',
    applicableBarrierIds: ['br-chm-001', 'br-chm-002'],
    criteria: 'Tank shell UT minimum thickness ≥ 8 mm. PSV test pass with set pressure tolerance ±3%.',
    source: 'API 653 / Internal MI program',
    version: '2.4',
    effectiveDate: '2024-09-01',
  },
  {
    id: 'ps-chm-002',
    scenarioId: 'sc-chemical',
    name: 'PS-CL-02 Chlorine release mitigation',
    category: 'response_time',
    applicableBarrierIds: ['br-chm-004', 'br-chm-005'],
    criteria: 'Detect → scrubber online within 30 s. Caustic strength sustained ≥ 18% NaOH.',
    source: 'EPA RMP / Internal SHE-12',
    version: '1.7',
    effectiveDate: '2025-03-01',
  },
];

export const CHEMICAL_INCIDENTS: Incident[] = [
  {
    id: 'in-chm-001',
    scenarioId: 'sc-chemical',
    title: 'Hose pressure test failure during routine inspection',
    date: '2025-12-01',
    severity: 'near_miss',
    description: 'Annual hose integrity test detected delamination on H-3 prior to use.',
    bowtieId: 'bt-chm-001',
    barrierFailures: ['br-chm-003'],
    learnings: 'Hose stewardship lapsed after barrier-owner departure. Establish interim custodian during transitions.',
    linkedActionIds: ['ac-chm-001', 'ac-chm-002'],
  },
];

export const CHEMICAL_MOCS: Moc[] = [
  {
    id: 'moc-chm-001',
    scenarioId: 'sc-chemical',
    title: 'Reassign barrier ownership — chlorine offloading procedure',
    changeType: 'organizational',
    status: 'in_review',
    affectedBowtieIds: ['bt-chm-001'],
    affectedBarrierIds: ['br-chm-003'],
    initiatedAt: '2026-04-05',
    ownerId: 'u-rm-001',
    riskAssessmentSummary:
      'Barrier owner departed company. Interim ownership with Plant 4 Operations Manager pending permanent assignment.',
  },
];

export const CHEMICAL_AUDITS: Audit[] = [
  {
    id: 'au-chm-001',
    scenarioId: 'sc-chemical',
    title: 'AUD-CHM-2026-Q1 Bulk hazardous storage',
    scope: 'Chlorine and EDC bulk storage areas; integrity, isolation, emergency response.',
    date: '2026-02-26',
    auditorId: 'u-au-001',
    findings: 2,
    status: 'closed',
  },
];

export const CHEMICAL_AI_SUGGESTIONS: AiSuggestion[] = [
  {
    id: 'ai-chm-001',
    promptHash: 'demo-hash-chm-001',
    modelId: 'demo-coach-v1',
    context: { type: 'risk_acceptance', targetId: 'rk-chm-001' },
    output: {
      title: 'Residual risk acceptance is "pending" while a critical barrier has no owner',
      rationale:
        'Bowtie bt-chm-001 has the offloading-procedure barrier in a gap state with no permanent owner. Per the methodology, accepting residual risk while a barrier ownership gap is open is not appropriate.',
      suggested:
        'Block ALARP acceptance for rk-chm-001 until moc-chm-001 closes and barrier br-chm-003 has a named permanent owner.',
      confidence: 'high',
      severity: 'blocker',
      citations: ['CCPS Bowtie Methodology §6.2', 'Internal SHE-12 §4.4'],
    },
    reviewerDecision: null,
    reviewerId: null,
    reviewedAt: null,
    createdAt: '2026-04-20',
  },
];
