import type {
  Action,
  Audit,
  Barrier,
  Bowtie,
  Consequence,
  DegradationControl,
  DegradationFactor,
  Incident,
  Moc,
  PerformanceStandard,
  Risk,
  Scenario,
  Threat,
  Verification,
  AiSuggestion,
} from '@bowtie/shared';

export const HOSPITAL_SCENARIO: Scenario = {
  id: 'sc-hospital',
  industry: 'hospital',
  name: 'St. Aldwyn Regional Hospital — General Surgery',
  description: '450-bed acute-care hospital; major elective and emergency surgery program.',
};

export const HOSPITAL_BOWTIES: Bowtie[] = [
  {
    id: 'bt-hsp-001',
    scenarioId: 'sc-hospital',
    title: 'Surgical Site Infection in Major Surgery',
    hazard: 'Patient surgical wound exposed to pathogens during and after surgery',
    topEvent: 'Bacterial contamination of surgical site',
    assetOrProcess: 'Operating Theatres 1–6; General Surgery ward',
    ownerId: 'u-bo-003',
    approvalState: 'internal_review',
    riskBeforeBarriers: 16,
    riskCurrent: 9,
    riskAfterBarriers: 6,
    riskTarget: 3,
    threatIds: ['th-hsp-001', 'th-hsp-002', 'th-hsp-003'],
    consequenceIds: ['cq-hsp-001', 'cq-hsp-002', 'cq-hsp-003'],
    preventiveBarrierIds: ['br-hsp-001', 'br-hsp-002', 'br-hsp-003'],
    mitigativeBarrierIds: ['br-hsp-004', 'br-hsp-005'],
    lastRevisedAt: '2026-04-12',
    nextReviewDue: '2026-10-12',
    changesPendingMoc: false,
    publishedAt: null,
  },
];

export const HOSPITAL_THREATS: Threat[] = [
  {
    id: 'th-hsp-001',
    bowtieId: 'bt-hsp-001',
    description: 'Inadequate antibiotic prophylaxis (timing, agent or dose)',
    preventiveBarrierIds: ['br-hsp-001'],
  },
  {
    id: 'th-hsp-002',
    bowtieId: 'bt-hsp-001',
    description: 'Skin antisepsis or surgical hand-prep failure',
    preventiveBarrierIds: ['br-hsp-002'],
  },
  {
    id: 'th-hsp-003',
    bowtieId: 'bt-hsp-001',
    description: 'Sterile field breach during procedure',
    preventiveBarrierIds: ['br-hsp-003'],
  },
];

export const HOSPITAL_CONSEQUENCES: Consequence[] = [
  {
    id: 'cq-hsp-001',
    bowtieId: 'bt-hsp-001',
    description: 'Sepsis with ICU admission',
    severity: 'major',
    mitigativeBarrierIds: ['br-hsp-004', 'br-hsp-005'],
  },
  {
    id: 'cq-hsp-002',
    bowtieId: 'bt-hsp-001',
    description: 'Reoperation and extended length of stay',
    severity: 'moderate',
    mitigativeBarrierIds: ['br-hsp-004'],
  },
  {
    id: 'cq-hsp-003',
    bowtieId: 'bt-hsp-001',
    description: 'Patient mortality',
    severity: 'catastrophic',
    mitigativeBarrierIds: ['br-hsp-005'],
  },
];

export const HOSPITAL_BARRIERS: Barrier[] = [
  {
    id: 'br-hsp-001',
    scenarioId: 'sc-hospital',
    bowtieIds: ['bt-hsp-001'],
    name: 'Prophylactic antibiotic protocol with timing checklist',
    type: 'preventive',
    function: 'procedural',
    criticality: 'critical',
    ownerId: 'u-bo-003',
    description: 'WHO surgical safety checklist; prophylactic antibiotic 30–60 min before incision.',
    performanceStandardId: 'ps-hsp-001',
    healthScore: 89,
    status: 'yellow',
    withCompensatory: false,
    lastVerifiedAt: '2026-03-01',
    nextVerificationDue: '2026-06-01',
    failedTests: 0,
    openCriticalFindings: 0,
    evidenceUrl: null,
    aiOriginSuggestionId: null,
    gapRecord: null,
  },
  {
    id: 'br-hsp-002',
    scenarioId: 'sc-hospital',
    bowtieIds: ['bt-hsp-001'],
    name: 'Skin antisepsis (chlorhexidine 2% / alcohol)',
    type: 'preventive',
    function: 'procedural',
    criticality: 'high',
    ownerId: 'u-bo-003',
    description: 'Chlorhexidine-alcohol skin prep with mandatory dry time before drape.',
    performanceStandardId: 'ps-hsp-001',
    healthScore: 93,
    status: 'green',
    withCompensatory: false,
    lastVerifiedAt: '2026-04-02',
    nextVerificationDue: '2026-10-02',
    failedTests: 0,
    openCriticalFindings: 0,
    evidenceUrl: null,
    aiOriginSuggestionId: null,
    gapRecord: null,
  },
  {
    id: 'br-hsp-003',
    scenarioId: 'sc-hospital',
    bowtieIds: ['bt-hsp-001'],
    name: 'Sterile technique training & competency',
    type: 'preventive',
    function: 'human',
    criticality: 'high',
    ownerId: 'u-bo-003',
    description: 'Annual competency assessment for theatre nurses and surgeons.',
    performanceStandardId: null,
    healthScore: 70,
    status: 'yellow',
    withCompensatory: false,
    lastVerifiedAt: '2025-09-01',
    nextVerificationDue: '2026-09-01',
    failedTests: 0,
    openCriticalFindings: 1,
    evidenceUrl: null,
    aiOriginSuggestionId: null,
    gapRecord: null,
  },
  {
    id: 'br-hsp-004',
    scenarioId: 'sc-hospital',
    bowtieIds: ['bt-hsp-001'],
    name: 'Post-op wound surveillance & early infection markers',
    type: 'mitigative',
    function: 'procedural',
    criticality: 'high',
    ownerId: 'u-bo-003',
    description: 'Daily wound check; CRP and WBC trend monitoring days 1–5.',
    performanceStandardId: 'ps-hsp-002',
    healthScore: 80,
    status: 'yellow',
    withCompensatory: false,
    lastVerifiedAt: '2026-03-22',
    nextVerificationDue: '2026-06-22',
    failedTests: 0,
    openCriticalFindings: 0,
    evidenceUrl: null,
    aiOriginSuggestionId: null,
    gapRecord: null,
  },
  {
    id: 'br-hsp-005',
    scenarioId: 'sc-hospital',
    bowtieIds: ['bt-hsp-001'],
    name: 'Antibiotic escalation + ICU support pathway',
    type: 'recovery',
    function: 'organizational',
    criticality: 'critical',
    ownerId: 'u-bo-003',
    description: 'Sepsis-six bundle + ICU rapid-response trigger.',
    performanceStandardId: null,
    healthScore: 92,
    status: 'green',
    withCompensatory: false,
    lastVerifiedAt: '2026-02-15',
    nextVerificationDue: '2026-08-15',
    failedTests: 0,
    openCriticalFindings: 0,
    evidenceUrl: null,
    aiOriginSuggestionId: null,
    gapRecord: null,
  },
];

export const HOSPITAL_DEGRADATION_FACTORS: DegradationFactor[] = [
  {
    id: 'df-hsp-001',
    barrierId: 'br-hsp-001',
    description: 'Antibiotic stockout during supply disruptions',
    degradationControlIds: ['dc-hsp-001'],
    aiOriginSuggestionId: null,
  },
  {
    id: 'df-hsp-002',
    barrierId: 'br-hsp-003',
    description: 'High locum / agency staff ratio reduces sterile-technique consistency',
    degradationControlIds: ['dc-hsp-002'],
    aiOriginSuggestionId: 'ai-hsp-001',
  },
];

export const HOSPITAL_DEGRADATION_CONTROLS: DegradationControl[] = [
  {
    id: 'dc-hsp-001',
    degradationFactorId: 'df-hsp-001',
    name: 'Approved alternative-antibiotic table with pharmacy escalation path',
    function: 'procedural',
    ownerId: 'u-bo-003',
    status: 'green',
    aiOriginSuggestionId: null,
  },
  {
    id: 'dc-hsp-002',
    degradationFactorId: 'df-hsp-002',
    name: 'Mandatory locum sterile-technique briefing + observed first case',
    function: 'organizational',
    ownerId: 'u-bo-003',
    status: 'yellow',
    aiOriginSuggestionId: 'ai-hsp-001',
  },
];

export const HOSPITAL_RISKS: Risk[] = [
  {
    id: 'rk-hsp-001',
    scenarioId: 'sc-hospital',
    title: 'Surgical site infection rate above target threshold',
    category: 'patient_safety',
    inherentRisk: 16,
    currentRisk: 9,
    residualRisk: 6,
    targetRisk: 3,
    ownerId: 'u-rm-001',
    bowtieIds: ['bt-hsp-001'],
    treatmentPlan: 'Address staffing-driven sterile-technique variability; close training gap.',
    acceptanceStatus: 'pending',
  },
];

export const HOSPITAL_ACTIONS: Action[] = [
  {
    id: 'ac-hsp-001',
    scenarioId: 'sc-hospital',
    title: 'Refresh sterile-technique training; remediate one finding from clinical audit',
    source: 'audit',
    bowtieId: 'bt-hsp-001',
    barrierId: 'br-hsp-003',
    ownerId: 'u-bo-003',
    dueDate: '2026-06-15',
    priority: 'high',
    status: 'in_progress',
    evidence: null,
    effectivenessReview: null,
  },
  {
    id: 'ac-hsp-002',
    scenarioId: 'sc-hospital',
    title: 'Add mandatory locum sterile-technique briefing to onboarding workflow',
    source: 'ai_suggestion',
    bowtieId: 'bt-hsp-001',
    barrierId: 'br-hsp-003',
    ownerId: 'u-bo-003',
    dueDate: '2026-05-30',
    priority: 'medium',
    status: 'open',
    evidence: null,
    effectivenessReview: null,
  },
];

export const HOSPITAL_VERIFICATIONS: Verification[] = [
  {
    id: 'vf-hsp-001',
    scenarioId: 'sc-hospital',
    date: '2026-03-01',
    barrierId: 'br-hsp-001',
    performedById: 'u-au-001',
    method: 'audit',
    result: 'partial',
    evidence: 'WHO checklist compliance audit Q1',
    nextDue: '2026-06-01',
    comments: 'Compliance 92%; timing window missed in 3 of 50 cases.',
  },
  {
    id: 'vf-hsp-002',
    scenarioId: 'sc-hospital',
    date: '2025-09-01',
    barrierId: 'br-hsp-003',
    performedById: 'u-au-001',
    method: 'document_review',
    result: 'partial',
    evidence: 'Theatre staff competency review',
    nextDue: '2026-09-01',
    comments: 'Locum cohort competency records incomplete; gap noted.',
  },
];

export const HOSPITAL_PERFORMANCE_STANDARDS: PerformanceStandard[] = [
  {
    id: 'ps-hsp-001',
    scenarioId: 'sc-hospital',
    name: 'PS-SSI-01 SSI prophylaxis bundle',
    category: 'reliability',
    applicableBarrierIds: ['br-hsp-001', 'br-hsp-002'],
    criteria: 'Prophylactic antibiotic administered 30–60 min pre-incision; chlorhexidine prep with full dry time.',
    source: 'WHO Surgical Safety Checklist v3 / Internal CG-22',
    version: '4.1',
    effectiveDate: '2025-04-01',
  },
  {
    id: 'ps-hsp-002',
    scenarioId: 'sc-hospital',
    name: 'PS-SSI-02 Post-op surveillance',
    category: 'response_time',
    applicableBarrierIds: ['br-hsp-004'],
    criteria: 'Wound check daily for 5 days; sepsis-six initiated within 1 h of trigger.',
    source: 'Royal College of Surgeons surveillance guideline',
    version: '2.0',
    effectiveDate: '2024-11-01',
  },
];

export const HOSPITAL_INCIDENTS: Incident[] = [
  {
    id: 'in-hsp-001',
    scenarioId: 'sc-hospital',
    title: 'SSI cluster — 3 cases over 6 weeks (general surgery)',
    date: '2026-03-12',
    severity: 'major',
    description: 'Three deep-incisional SSIs identified post-discharge over six weeks; root-cause analysis in progress.',
    bowtieId: 'bt-hsp-001',
    barrierFailures: ['br-hsp-003'],
    learnings: 'Cluster timing aligns with elevated locum ratio. Drives DF "High locum / agency staff ratio".',
    linkedActionIds: ['ac-hsp-001', 'ac-hsp-002'],
  },
];

export const HOSPITAL_MOCS: Moc[] = [];

export const HOSPITAL_AUDITS: Audit[] = [
  {
    id: 'au-hsp-001',
    scenarioId: 'sc-hospital',
    title: 'AUD-HSP-2026-Q1 SSI prevention bundle audit',
    scope: 'Surgical safety checklist compliance and sterile technique observation across OT 1–6.',
    date: '2026-03-15',
    auditorId: 'u-au-001',
    findings: 3,
    status: 'closed',
  },
];

export const HOSPITAL_AI_SUGGESTIONS: AiSuggestion[] = [
  {
    id: 'ai-hsp-001',
    promptHash: 'demo-hash-hsp-001',
    modelId: 'demo-coach-v1',
    context: { type: 'degradation_factor', targetId: 'br-hsp-003' },
    output: {
      title: 'Add a degradation factor for high locum / agency staff ratio',
      rationale:
        'Recent SSI cluster (in-hsp-001) coincides with elevated locum ratio in general surgery. Sterile-technique consistency is a known degradation mechanism for the staff-competency barrier in healthcare settings.',
      suggested:
        'Add Degradation Factor "High locum / agency staff ratio" linked to barrier br-hsp-003, with Degradation Control "Mandatory locum sterile-technique briefing + observed first case".',
      confidence: 'medium',
      severity: 'warning',
      citations: ['WHO Surgical Safety Checklist v3', 'Internal RCA RCA-2026-03-12'],
    },
    reviewerDecision: null,
    reviewerId: null,
    reviewedAt: null,
    createdAt: '2026-04-22',
  },
];
