import type {
  Action,
  Audit,
  Barrier,
  Bowtie,
  Consequence,
  DegradationControl,
  DegradationFactor,
  Incident,
  Moc,
  PerformanceStandard,
  Risk,
  Scenario,
  Threat,
  Verification,
  AiSuggestion,
} from '@bowtie/shared';

export const OFFSHORE_SCENARIO: Scenario = {
  id: 'sc-offshore',
  industry: 'offshore_oil',
  name: 'Northstar Bravo Platform',
  description: 'North Sea fixed offshore production platform — 18,000 bbl/d.',
};

export const OFFSHORE_BOWTIES: Bowtie[] = [
  {
    id: 'bt-off-001',
    scenarioId: 'sc-offshore',
    title: 'Hydrocarbon Release on Topsides',
    hazard: 'Hydrocarbon under pressure (process equipment, modules M20–M40)',
    topEvent: 'Loss of containment of hydrocarbon from process equipment',
    assetOrProcess: 'Topsides process modules M20–M40',
    ownerId: 'u-bo-001',
    approvalState: 'published',
    riskBeforeBarriers: 24,
    riskCurrent: 12,
    riskAfterBarriers: 8,
    riskTarget: 4,
    threatIds: ['th-off-001', 'th-off-002', 'th-off-003', 'th-off-004'],
    consequenceIds: ['cq-off-001', 'cq-off-002', 'cq-off-003'],
    preventiveBarrierIds: ['br-off-001', 'br-off-002', 'br-off-003', 'br-off-004'],
    mitigativeBarrierIds: ['br-off-005', 'br-off-006', 'br-off-007', 'br-off-008'],
    lastRevisedAt: '2026-02-14',
    nextReviewDue: '2026-08-14',
    changesPendingMoc: false,
    publishedAt: '2025-11-02',
  },
];

export const OFFSHORE_THREATS: Threat[] = [
  {
    id: 'th-off-001',
    bowtieId: 'bt-off-001',
    description: 'Internal corrosion of process piping',
    preventiveBarrierIds: ['br-off-001', 'br-off-002'],
  },
  {
    id: 'th-off-002',
    bowtieId: 'bt-off-001',
    description: 'Mechanical impact during lifting operations',
    preventiveBarrierIds: ['br-off-003'],
  },
  {
    id: 'th-off-003',
    bowtieId: 'bt-off-001',
    description: 'Operator error during isolation / line breaking',
    preventiveBarrierIds: ['br-off-003', 'br-off-004'],
  },
  {
    id: 'th-off-004',
    bowtieId: 'bt-off-001',
    description: 'Wrong valve actuation in process control',
    preventiveBarrierIds: ['br-off-004'],
  },
];

export const OFFSHORE_CONSEQUENCES: Consequence[] = [
  {
    id: 'cq-off-001',
    bowtieId: 'bt-off-001',
    description: 'Pool fire / vapour cloud explosion on topsides',
    severity: 'catastrophic',
    mitigativeBarrierIds: ['br-off-005', 'br-off-006', 'br-off-007'],
  },
  {
    id: 'cq-off-002',
    bowtieId: 'bt-off-001',
    description: 'Toxic exposure to personnel (H2S co-release)',
    severity: 'major',
    mitigativeBarrierIds: ['br-off-005', 'br-off-008'],
  },
  {
    id: 'cq-off-003',
    bowtieId: 'bt-off-001',
    description: 'Hydrocarbon discharge to sea — environmental harm',
    severity: 'major',
    mitigativeBarrierIds: ['br-off-007'],
  },
];

export const OFFSHORE_BARRIERS: Barrier[] = [
  // Preventive
  {
    id: 'br-off-001',
    scenarioId: 'sc-offshore',
    bowtieIds: ['bt-off-001'],
    name: 'Risk-Based Inspection (RBI) program',
    type: 'preventive',
    function: 'procedural',
    criticality: 'critical',
    ownerId: 'u-bo-001',
    description: 'Risk-based inspection of pressurised piping per API 580.',
    performanceStandardId: 'ps-off-001',
    healthScore: 88,
    status: 'yellow',
    withCompensatory: false,
    lastVerifiedAt: '2026-01-22',
    nextVerificationDue: '2026-07-22',
    failedTests: 0,
    openCriticalFindings: 0,
    evidenceUrl: null,
    aiOriginSuggestionId: null,
    gapRecord: null,
  },
  {
    id: 'br-off-002',
    scenarioId: 'sc-offshore',
    bowtieIds: ['bt-off-001'],
    name: 'Corrosion monitoring & inhibitor injection',
    type: 'preventive',
    function: 'instrumented',
    criticality: 'high',
    ownerId: 'u-bo-001',
    description: 'Online corrosion monitoring with inhibitor dosing on flowlines.',
    performanceStandardId: null,
    healthScore: 94,
    status: 'green',
    withCompensatory: false,
    lastVerifiedAt: '2026-03-10',
    nextVerificationDue: '2026-09-10',
    failedTests: 0,
    openCriticalFindings: 0,
    evidenceUrl: null,
    aiOriginSuggestionId: null,
    gapRecord: null,
  },
  {
    id: 'br-off-003',
    scenarioId: 'sc-offshore',
    bowtieIds: ['bt-off-001'],
    name: 'Permit-to-Work (PTW) system',
    type: 'preventive',
    function: 'organizational',
    criticality: 'critical',
    ownerId: 'u-bo-001',
    description: 'Permit-to-work and isolation control for hot work and line breaking.',
    performanceStandardId: 'ps-off-002',
    healthScore: 45,
    status: 'red',
    /** Compensated red — extra OIM-led permit oversight in place after audit finding. */
    withCompensatory: true,
    compensatoryNotes: 'OIM-led permit oversight implemented since audit AUD-OFF-001. Stays Red until root cause closed.',
    lastVerifiedAt: '2026-03-30',
    nextVerificationDue: '2026-04-15',
    failedTests: 1,
    openCriticalFindings: 2,
    evidenceUrl: null,
    aiOriginSuggestionId: null,
    gapRecord: null,
  },
  {
    id: 'br-off-004',
    scenarioId: 'sc-offshore',
    bowtieIds: ['bt-off-001'],
    name: 'Operator competency assurance',
    type: 'preventive',
    function: 'human',
    criticality: 'high',
    ownerId: 'u-bo-001',
    description: 'Competency assurance for control-room and field operators.',
    performanceStandardId: null,
    healthScore: 72,
    status: 'yellow',
    withCompensatory: false,
    lastVerifiedAt: '2025-11-05',
    nextVerificationDue: '2026-05-05',
    failedTests: 0,
    openCriticalFindings: 1,
    evidenceUrl: null,
    aiOriginSuggestionId: null,
    gapRecord: null,
  },
  // Mitigative
  {
    id: 'br-off-005',
    scenarioId: 'sc-offshore',
    bowtieIds: ['bt-off-001'],
    name: 'Fire & Gas (F&G) detection',
    type: 'mitigative',
    function: 'instrumented',
    criticality: 'critical',
    ownerId: 'u-bo-001',
    description: 'Fire & gas detection with voting logic on topsides.',
    performanceStandardId: 'ps-off-001',
    healthScore: 91,
    status: 'green',
    withCompensatory: false,
    lastVerifiedAt: '2026-04-02',
    nextVerificationDue: '2026-10-02',
    failedTests: 0,
    openCriticalFindings: 0,
    evidenceUrl: null,
    aiOriginSuggestionId: null,
    gapRecord: null,
  },
  {
    id: 'br-off-006',
    scenarioId: 'sc-offshore',
    bowtieIds: ['bt-off-001'],
    name: 'Emergency Shutdown System (ESD)',
    type: 'mitigative',
    function: 'instrumented',
    criticality: 'critical',
    ownerId: 'u-bo-001',
    description: 'SIL-2 ESD with logic solver and final elements.',
    performanceStandardId: 'ps-off-001',
    healthScore: 96,
    status: 'green',
    withCompensatory: false,
    lastVerifiedAt: '2026-02-28',
    nextVerificationDue: '2026-08-28',
    failedTests: 0,
    openCriticalFindings: 0,
    evidenceUrl: null,
    aiOriginSuggestionId: null,
    gapRecord: null,
  },
  {
    id: 'br-off-007',
    scenarioId: 'sc-offshore',
    bowtieIds: ['bt-off-001'],
    name: 'Active fire suppression — deluge',
    type: 'mitigative',
    function: 'hardware',
    criticality: 'critical',
    ownerId: 'u-bo-001',
    description: 'Topsides deluge with seawater lift pumps (2x100%).',
    performanceStandardId: null,
    healthScore: 65,
    status: 'red',
    withCompensatory: false,
    lastVerifiedAt: '2025-09-12',
    nextVerificationDue: '2026-03-12',
    failedTests: 0,
    openCriticalFindings: 1,
    evidenceUrl: null,
    aiOriginSuggestionId: null,
    gapRecord: null,
  },
  {
    id: 'br-off-008',
    scenarioId: 'sc-offshore',
    bowtieIds: ['bt-off-001'],
    name: 'Emergency response & muster',
    type: 'recovery',
    function: 'organizational',
    criticality: 'high',
    ownerId: 'u-bo-001',
    description: 'Emergency response, muster discipline, lifeboat readiness.',
    performanceStandardId: null,
    healthScore: 82,
    status: 'yellow',
    withCompensatory: false,
    lastVerifiedAt: '2026-02-10',
    nextVerificationDue: '2026-08-10',
    failedTests: 0,
    openCriticalFindings: 0,
    evidenceUrl: null,
    aiOriginSuggestionId: null,
    gapRecord: null,
  },
];

export const OFFSHORE_DEGRADATION_FACTORS: DegradationFactor[] = [
  {
    id: 'df-off-001',
    barrierId: 'br-off-003',
    description: 'Permit fatigue during 14/14 rotation — late-shift quality drop',
    degradationControlIds: ['dc-off-001'],
    aiOriginSuggestionId: 'ai-off-001',
  },
  {
    id: 'df-off-002',
    barrierId: 'br-off-007',
    description: 'Seawater pump suction strainer fouling in summer months',
    degradationControlIds: ['dc-off-002'],
    aiOriginSuggestionId: null,
  },
];

export const OFFSHORE_DEGRADATION_CONTROLS: DegradationControl[] = [
  {
    id: 'dc-off-001',
    degradationFactorId: 'df-off-001',
    name: 'Mandatory dual-signoff for night-shift hot-work permits',
    function: 'organizational',
    ownerId: 'u-bo-001',
    status: 'yellow',
    aiOriginSuggestionId: null,
  },
  {
    id: 'dc-off-002',
    degradationFactorId: 'df-off-002',
    name: 'Quarterly strainer cleaning + condition monitoring',
    function: 'procedural',
    ownerId: 'u-bo-001',
    status: 'green',
    aiOriginSuggestionId: null,
  },
];

export const OFFSHORE_RISKS: Risk[] = [
  {
    id: 'rk-off-001',
    scenarioId: 'sc-offshore',
    title: 'Major hydrocarbon release with ignition (topsides)',
    category: 'safety',
    inherentRisk: 24,
    currentRisk: 12,
    residualRisk: 8,
    targetRisk: 4,
    ownerId: 'u-rm-001',
    bowtieIds: ['bt-off-001'],
    treatmentPlan: 'Strengthen PTW oversight; restore deluge availability; close audit findings AUD-OFF-001.',
    acceptanceStatus: 'alarp_justified',
  },
  {
    id: 'rk-off-002',
    scenarioId: 'sc-offshore',
    title: 'Crude release to sea from process drains',
    category: 'environmental',
    inherentRisk: 16,
    currentRisk: 8,
    residualRisk: 5,
    targetRisk: 3,
    ownerId: 'u-rm-001',
    bowtieIds: ['bt-off-001'],
    treatmentPlan: 'Closed-drain-system integrity verification each turnaround.',
    acceptanceStatus: 'accepted',
  },
];

export const OFFSHORE_ACTIONS: Action[] = [
  {
    id: 'ac-off-001',
    scenarioId: 'sc-offshore',
    title: 'Restore topsides deluge availability — replace lift pump #2 mechanical seal',
    source: 'verification',
    bowtieId: 'bt-off-001',
    barrierId: 'br-off-007',
    ownerId: 'u-bo-001',
    dueDate: '2026-05-20',
    priority: 'critical',
    status: 'in_progress',
    evidence: null,
    effectivenessReview: null,
  },
  {
    id: 'ac-off-002',
    scenarioId: 'sc-offshore',
    title: 'Close out PTW audit findings — strengthen lockout/tagout step',
    source: 'audit',
    bowtieId: 'bt-off-001',
    barrierId: 'br-off-003',
    ownerId: 'u-bo-001',
    dueDate: '2026-04-30',
    priority: 'critical',
    status: 'overdue',
    evidence: null,
    effectivenessReview: null,
  },
  {
    id: 'ac-off-003',
    scenarioId: 'sc-offshore',
    title: 'Refresh operator competency assessment for control room shift leads',
    source: 'review',
    bowtieId: 'bt-off-001',
    barrierId: 'br-off-004',
    ownerId: 'u-bo-001',
    dueDate: '2026-06-30',
    priority: 'high',
    status: 'open',
    evidence: null,
    effectivenessReview: null,
  },
];

export const OFFSHORE_VERIFICATIONS: Verification[] = [
  {
    id: 'vf-off-001',
    scenarioId: 'sc-offshore',
    date: '2026-04-02',
    barrierId: 'br-off-005',
    performedById: 'u-bo-001',
    method: 'test',
    result: 'pass',
    evidence: 'F&G loop test — Q2 2026',
    nextDue: '2026-10-02',
    comments: 'All voting logic functional; minor drift on detector M22-GD-103.',
  },
  {
    id: 'vf-off-002',
    scenarioId: 'sc-offshore',
    date: '2026-03-30',
    barrierId: 'br-off-003',
    performedById: 'u-au-001',
    method: 'audit',
    result: 'fail',
    evidence: 'Audit AUD-OFF-001',
    nextDue: '2026-04-15',
    comments: 'Two PTW signoff inconsistencies on hot work; root cause: night-shift fatigue.',
  },
  {
    id: 'vf-off-003',
    scenarioId: 'sc-offshore',
    date: '2025-09-12',
    barrierId: 'br-off-007',
    performedById: 'u-bo-001',
    method: 'test',
    result: 'partial',
    evidence: 'Deluge wet test report',
    nextDue: '2026-03-12',
    comments: 'Lift pump #2 underperforming — flow 78% of rated.',
  },
];

export const OFFSHORE_PERFORMANCE_STANDARDS: PerformanceStandard[] = [
  {
    id: 'ps-off-001',
    scenarioId: 'sc-offshore',
    name: 'PS-001 Detect & Shutdown',
    category: 'response_time',
    applicableBarrierIds: ['br-off-005', 'br-off-006'],
    criteria: 'Detect → Confirm → Shutdown within 30 s for confirmed gas at >40% LEL.',
    source: 'NORSOK S-001 / Internal SIS spec',
    version: '3.2',
    effectiveDate: '2024-06-01',
  },
  {
    id: 'ps-off-002',
    scenarioId: 'sc-offshore',
    name: 'PS-002 Permit-to-Work',
    category: 'reliability',
    applicableBarrierIds: ['br-off-003'],
    criteria: 'Two-person signoff on all hot-work permits. Permit-to-work register reconciled daily.',
    source: 'Internal Operations Manual OM-12',
    version: '5.0',
    effectiveDate: '2025-01-15',
  },
];

export const OFFSHORE_INCIDENTS: Incident[] = [
  {
    id: 'in-off-001',
    scenarioId: 'sc-offshore',
    title: 'Small hydrocarbon leak — flange weep on M30 separator',
    date: '2026-02-08',
    severity: 'minor',
    description: 'Weeping flange detected during routine walkround; ~50 ml/min liquid HC.',
    bowtieId: 'bt-off-001',
    barrierFailures: ['br-off-001'],
    learnings: 'RBI inspection interval too long for high-temperature service flanges. Tighten interval.',
    linkedActionIds: [],
  },
  {
    id: 'in-off-002',
    scenarioId: 'sc-offshore',
    title: 'PTW step skipped — near miss during line breaking',
    date: '2026-03-25',
    severity: 'near_miss',
    description: 'Line breaking commenced while a downstream block valve had not been verified closed.',
    bowtieId: 'bt-off-001',
    barrierFailures: ['br-off-003'],
    learnings: 'Permit handover at shift change incomplete; verbal handover not corroborated against permit register.',
    linkedActionIds: ['ac-off-002'],
  },
];

export const OFFSHORE_MOCS: Moc[] = [];

export const OFFSHORE_AUDITS: Audit[] = [
  {
    id: 'au-off-001',
    scenarioId: 'sc-offshore',
    title: 'AUD-OFF-001 Permit-to-Work effectiveness audit',
    scope: 'PTW process and night-shift execution; modules M20–M40.',
    date: '2026-03-30',
    auditorId: 'u-au-001',
    findings: 4,
    status: 'reporting',
  },
];

export const OFFSHORE_AI_SUGGESTIONS: AiSuggestion[] = [
  {
    id: 'ai-off-001',
    promptHash: 'demo-hash-off-001',
    modelId: 'demo-coach-v1',
    context: { type: 'degradation_factor', targetId: 'br-off-003' },
    output: {
      title: 'Add a degradation factor for permit fatigue',
      rationale:
        'Audit finding cites two night-shift PTW errors. The current bowtie has no Degradation Factor for permit fatigue, leaving the PTW barrier exposed to a recurring degradation mechanism.',
      suggested:
        'Add Degradation Factor "Permit fatigue during 14/14 rotation" with Degradation Control "Mandatory dual-signoff for night-shift hot-work permits".',
      confidence: 'high',
      severity: 'warning',
      citations: ['CCPS Bowtie Methodology §4.3', 'Internal audit AUD-OFF-001'],
    },
    reviewerDecision: 'accepted',
    reviewerId: 'u-rm-001',
    reviewedAt: '2026-04-04',
    createdAt: '2026-04-01',
  },
];
