import type { DemoState } from '@bowtie/shared';

import { DEFAULT_USER_ID, SEED_USERS } from './users';
import { SEED_TEMPLATES } from './templates';
import {
  OFFSHORE_SCENARIO,
  OFFSHORE_BOWTIES,
  OFFSHORE_THREATS,
  OFFSHORE_CONSEQUENCES,
  OFFSHORE_BARRIERS,
  OFFSHORE_DEGRADATION_FACTORS,
  OFFSHORE_DEGRADATION_CONTROLS,
  OFFSHORE_RISKS,
  OFFSHORE_ACTIONS,
  OFFSHORE_VERIFICATIONS,
  OFFSHORE_PERFORMANCE_STANDARDS,
  OFFSHORE_INCIDENTS,
  OFFSHORE_MOCS,
  OFFSHORE_AUDITS,
  OFFSHORE_AI_SUGGESTIONS,
} from './scenarios/offshore';
import {
  CHEMICAL_SCENARIO,
  CHEMICAL_BOWTIES,
  CHEMICAL_THREATS,
  CHEMICAL_CONSEQUENCES,
  CHEMICAL_BARRIERS,
  CHEMICAL_DEGRADATION_FACTORS,
  CHEMICAL_DEGRADATION_CONTROLS,
  CHEMICAL_RISKS,
  CHEMICAL_ACTIONS,
  CHEMICAL_VERIFICATIONS,
  CHEMICAL_PERFORMANCE_STANDARDS,
  CHEMICAL_INCIDENTS,
  CHEMICAL_MOCS,
  CHEMICAL_AUDITS,
  CHEMICAL_AI_SUGGESTIONS,
} from './scenarios/chemical';
import {
  HOSPITAL_SCENARIO,
  HOSPITAL_BOWTIES,
  HOSPITAL_THREATS,
  HOSPITAL_CONSEQUENCES,
  HOSPITAL_BARRIERS,
  HOSPITAL_DEGRADATION_FACTORS,
  HOSPITAL_DEGRADATION_CONTROLS,
  HOSPITAL_RISKS,
  HOSPITAL_ACTIONS,
  HOSPITAL_VERIFICATIONS,
  HOSPITAL_PERFORMANCE_STANDARDS,
  HOSPITAL_INCIDENTS,
  HOSPITAL_MOCS,
  HOSPITAL_AUDITS,
  HOSPITAL_AI_SUGGESTIONS,
} from './scenarios/hospital';

export const SCHEMA_VERSION = 2;

export function buildSeedState(): DemoState {
  return {
    schemaVersion: SCHEMA_VERSION,
    currentUserId: DEFAULT_USER_ID,
    scenarios: [OFFSHORE_SCENARIO, CHEMICAL_SCENARIO, HOSPITAL_SCENARIO],
    users: SEED_USERS,
    bowties: [...OFFSHORE_BOWTIES, ...CHEMICAL_BOWTIES, ...HOSPITAL_BOWTIES],
    threats: [...OFFSHORE_THREATS, ...CHEMICAL_THREATS, ...HOSPITAL_THREATS],
    consequences: [...OFFSHORE_CONSEQUENCES, ...CHEMICAL_CONSEQUENCES, ...HOSPITAL_CONSEQUENCES],
    barriers: [...OFFSHORE_BARRIERS, ...CHEMICAL_BARRIERS, ...HOSPITAL_BARRIERS],
    degradationFactors: [
      ...OFFSHORE_DEGRADATION_FACTORS,
      ...CHEMICAL_DEGRADATION_FACTORS,
      ...HOSPITAL_DEGRADATION_FACTORS,
    ],
    degradationControls: [
      ...OFFSHORE_DEGRADATION_CONTROLS,
      ...CHEMICAL_DEGRADATION_CONTROLS,
      ...HOSPITAL_DEGRADATION_CONTROLS,
    ],
    risks: [...OFFSHORE_RISKS, ...CHEMICAL_RISKS, ...HOSPITAL_RISKS],
    actions: [...OFFSHORE_ACTIONS, ...CHEMICAL_ACTIONS, ...HOSPITAL_ACTIONS],
    verifications: [...OFFSHORE_VERIFICATIONS, ...CHEMICAL_VERIFICATIONS, ...HOSPITAL_VERIFICATIONS],
    performanceStandards: [
      ...OFFSHORE_PERFORMANCE_STANDARDS,
      ...CHEMICAL_PERFORMANCE_STANDARDS,
      ...HOSPITAL_PERFORMANCE_STANDARDS,
    ],
    incidents: [...OFFSHORE_INCIDENTS, ...CHEMICAL_INCIDENTS, ...HOSPITAL_INCIDENTS],
    mocs: [...OFFSHORE_MOCS, ...CHEMICAL_MOCS, ...HOSPITAL_MOCS],
    audits: [...OFFSHORE_AUDITS, ...CHEMICAL_AUDITS, ...HOSPITAL_AUDITS],
    templates: SEED_TEMPLATES,
    aiSuggestions: [...OFFSHORE_AI_SUGGESTIONS, ...CHEMICAL_AI_SUGGESTIONS, ...HOSPITAL_AI_SUGGESTIONS],
    wizardDraft: null,
  };
}
